module.exports = {
    nTextNext: 'Next',
    nTextDone: 'Done',
    nTextGuideNavArea: 'This is the nav zone',
    nTextGuideNavOrderCenter: 'You can see all the inquiries and orders sorting by vessels and sailing date',
    nTextGuideNavQuotation:'In this nav you could see quotes from agents',
    nTextGuideNavShip: 'You can see the vessels and fleets',
    nTextGuideNavOrder: 'In this nav you could see orders in service',
    nTextGuideNavUser: 'This column is about private information and personal preference setting',
    nTextGuideNavSystem: 'This column is about company information\\\\registeration\\\\org structure setting\\\\bank account',
    nTextGuideHeader: 'The top nav is about notifications and user guide',
    nTextGuideHeaderNotification: 'This is the notification box, all the messages shall be presents here. You could click to confirm or enter a certain page',
    nTextGuideHeaderNotificationDetail: 'For principals or clients messages shall be sent to the message box when any quote or order occurs. Click the message to enter a certain page to conduct.',
    nTextGuideHeaderHelp: 'This the user guide document',
    nTextGuideHeaderUser: 'Here is the entrance of a personal center, you could modify own information or log out',
    nTextGuideAddInquiry: 'Click here to add an inquiry',
    nTextGuidePortAndServiceSelectPort: 'Click here to select a port',
    nTextGuidePortAndServiceAddPort:'Click here to add a new port',
    nTextGuidePortAndServiceOrderType:'Click here to add a Order Type',
    nTextGuidePortAndServiceDatePicker:'Click here to add a ETA time',
    nTextGuidePortAndServiceTerminal:'Click here to add a terminal',
    nTextGuidePortAndServiceSave:'Click the button to submit and go to inquiry setting page',
    nTextGuidePortAndServiceAddCustomService: 'Click here to add a custom service',
    nTextGuideFavShipPriceInquiry: 'Click to see inquiries',
    nTextGuideFavShipOrder: 'Click to see orders',
    nTextGuideFavShipSearchShip: 'Input IMO or vessel name to search a vessel',
    nTextGuideFavShipFavorite: 'Click here to follow or unfollow a ship',
    nTextGuideVoyageInquiryTimeLine: 'Select a sailing date to see the service details by the right side',
    nTextGuideVoyageOrderTimeLine: 'Select a sailing date to see the service details by the right side',
    nTextGuideInquiryDetailAddServiceItem: 'Click here to add a new service item',
    nTextGuideInquiryDetailServiceList: 'Click this area to shift service item',
    nTextGuideInquiryDetailRemoveInquiry: 'Click this button to delete previous inquiry',
    nTextGuideInquiryDetailPublishInquiry: 'Click the button to send inquiries to agents when setting work finished',
    nTextGuideInquiryDetailContinuePublishInquiry: 'Click the button to send inquiries to other agents',
    nTextGuideInquiryDetailQuoteNow: 'Click here to submit a quotation',
    nTextGuideInquiryDetailMore: 'Click here to see more information',
    nTextGuideListTableViewEportsPrice: 'Click here to see e-ports quotes for reference',
    nTextGuideListTableViewAgentPrice: 'Click here to see quotes from agents',
    nTextGuideQuotationAppointAgent: 'Click the button to appoint the agent and generate an order',
    nTextGuideQuotationReQuote: 'Click the button to make it a new quote.',
    nTextGuideQuotationMessageInput: 'This area is about message functions. Message record shall be present here as a list',
    nTextGuideBillActualCost: 'All quotes in total from agents shall be present here, they add up to an FDA',
    nTextGuideBillPreActualCost: 'All quotes in total from agents shall be present here, they add up to an (Estimated) FDA',
    nTextGuideBillAccountFor: 'Here is the beneficiary information',
    nTextGuideBillAccountFrom: 'Here is the payer information, you could choose to pay to agents or to e-ports',
    nTextGuideBillBillStatus: 'Order statement(recently waiting to submit), when all quotes of the service items were filled, the statement will turn to be submitted',
    nTextGuideBillchat: 'It is an instant message function. You could make instant communication while any problem occurs.',
    nTextGuideBillRejectBill: 'Here is the function to accept or refuse the bill. You could refuse and make agents modify the bill until you both make an agreement',
    nTextGuideBillAcceptBill: 'Click here to accept the bill',
    nTextGuideBillBankAccount: 'This is agent\' payment account.You could pay to this account when it is not void',
    nTextGuideBillInformEports: 'If you choose to pay to e-ports platform. Please click this button when you finished the remittance',
    nTextGuideHeaderAddShip: 'Click here to add a ship',
    nTextGuideShipOperation: 'This area is about editing ship information. Modification\\\\sent to verify\\\\disconnecting the ship\\\\setting PIC',
    nTextGuideHeaderAddFleet: 'Click to add a fleet',
    nTextGuideFleetOperation: 'Click this area to edit or modify the fleet information',
    nTextGuideUserEditPassword: 'Click here to modify your password',
    nTextGuideUserViewPermissions: 'Click here to transfer administer to other person',
    nTextGuidePermissionAddPosition:'Click the button to add a role and endue it authorities',
    nTextGuidePermissionBatches: 'Select the roles to delete, press the button to delete',
    nTextGuidePermissionOperation: 'Click this area to edit or modify roles\' authorities',
    nTextGuideOrganizationAddDept: 'Click to add an department',
    nTextGuideOrganizationStaff: 'Click to add an user to the company',
    nTextGuideOrganizationEditDeptBatch: 'Click to modify certain user\'s department',
    nTextGuideOrganizationEditPositionBatch: 'Click to modify certain users\' position',
    nTextGuideOrganizationOperation: 'This area is about editing users\' authorities or deleting him',
    nTextGuideQuotationInquiryStatus: 'Click here to shift quote statement',
    nTextGuideQuotationEpcard: 'Click to the specific page for service item quoting',
    nTextGuideQuotationDetail: 'Click to see specific information of quoted item',
    nTextGuideQuotationAddCost: 'Click to unfold and add a fee type, edit and save',
    nTextGuideOrderStatus: 'Click to shift to differed types of orders',
    nTextGuideOrderEpcard: 'Click here to see details of a order',
    nTextGuideOrderOrderStatusLabel: 'Click to see statement of a order',
    nTextGuideOrderDetailViewReport: 'Click to enter a new page and send reports to principals',
    nTextGuideOrderDetailViewReportPrincipal: 'Click to enter a new page and view reports',
    nTextGuideOrderDetailAddService: 'Click here to add a new service item including customized service items',
    nTextGuideOrderDetailOrderCard: 'Click here to modify service information of the order, including service type\\\\vessel name\\\\sailing date\\\\principal information, also modify sailing date by hand ',
    nTextGuideOrderDetailServiceList: 'Click to shift a service item',
    nTextGuideOrderDetailEdit: 'Click to open authorities of editing, click to save when submitting is needed',
    nTextGuideOrderDetailMore: 'Click the button to set up messaging setting\\\\pic\\\\viewing notifications\\\\viewing operating log',
    nTextGuideOrderDetailViewBill: 'Click to see details of the bill',
    nTextGuideOrderDetailChat:'It is an instant message function. You could make instant communication while any problem occurs.',
    nTextGuideOrderDetailOrderEntryOperation: 'This is the work flow of the service item, click to finished this section and get into the next until all sections finished. When all service items finished you could send bill to principals',
    nTextGuideOrderDetailLogItemList: 'Click the left side to shift the service items and write reports of them',
    nTextGuideOrderDetailLogItemListView:'Click the left side to shift the service items and view reports of them',
    nTextGuideOrderDetailUpload: 'It\'s a uploading entry of attachments by the right side',
    nTextGuideOrderDetailUploadPrincipal: 'You can see report attachments here',
    nTextGuideOrderDetailSendReport: 'Click the button to send reports to principals'
}
