//default : circle: false, position: right, covered: true

module.exports = {
  'leftNav.list': {
    content: 'nTextGuideNavArea',
    index:1,
  },
  'leftNav.dashboard': {
    content: 'nTextGuideNavOrderCenter',
    index: 2,
  },
  'leftNav.quotation': {
    content: 'nTextGuideNavQuotation',
    index: 2,
  },
  'leftNav.ship': {
    content: 'nTextGuideNavShip',
    index: 3,
  },
  'leftNav.order': {
    content: 'nTextGuideNavOrder',
    index: 3,
  },
  'leftNav.center': {
    content: 'nTextGuideNavUser',
    index: 4,
  },
  'leftNav.user': {
    content: 'nTextGuideNavUser',
    index: 5,
  },
  'leftNav.settings': {
    content: 'nTextGuideNavSystem',
    index: 6,
  },
  'header.header': {
    content: 'nTextGuideHeader',
    position: "bottom",
    index: 7,
  },
  'header.notification': {
    content: 'nTextGuideHeaderNotification',
    position: "left",
    index: 8,
  },
  'header.notificationDetail': {
    content: 'nTextGuideHeaderNotificationDetail',
    position: "left",
    index: 8,
  },
  'header.help': {
    content: 'nTextGuideHeaderHelp',
    position: "left",
    circle: true,
    index: 9,
  },
  'header.user': {
    content: 'nTextGuideHeaderUser',
    position: "left",
    circle: true,
    index: 10,
  },
  'header.addInquiry': {
    content: 'nTextGuideAddInquiry',
    position: "bottom",
    covered: false,
    index: 11,
  },
  'portAndService.selectPort': {
    content: 'nTextGuidePortAndServiceSelectPort',
    position: "bottom",
    covered: false,
    index: 12,
  },
  'portAndService.addPort': {
    content: 'nTextGuidePortAndServiceAddPort',
    position: "left",
    covered: false,
    index: 13,
  },
  'portAndService.orderType': {
    content: 'nTextGuidePortAndServiceOrderType',
    position: "bottom",
    covered: false,
    index: 14,
  },
  'portAndService.datePicker': {
    content: 'nTextGuidePortAndServiceDatePicker',
    position: "bottom",
    covered: false,
    index: 15,
  },
  'portAndService.terminal': {
    content: 'nTextGuidePortAndServiceTerminal',
    position: "bottom",
    covered: false,
    index: 16,
  },
  'portAndService.save': {
    content: 'nTextGuidePortAndServiceSave',
    position: "bottom",
    covered: false,
    index: 17,
  },
  'portAndService.addCustomService': {
    content: 'nTextGuidePortAndServiceAddCustomService',
    position: "bottom",
    covered: false,
    index: 17,
  },
  'favShip.priceInquiry': {
    content: 'nTextGuideFavShipPriceInquiry',
    position: "bottom",
    covered: false,
    index: 18,
  },
  'favShip.order': {
    content: 'nTextGuideFavShipOrder',
    position: "bottom",
    covered: false,
    index: 19,
  },
  'favShip.addInquiry': {
    content: 'nTextGuideAddInquiry',
    position: "bottom",
    covered: false,
    index: 20,
  },
  'favShip.searchShip': {
    content: 'nTextGuideFavShipSearchShip',
    position: "bottom",
    covered: false,
    index: 21,
  },
  'favShip.favorite': {
    content: 'nTextGuideFavShipFavorite',
    position: "right",
    covered: false,
    index: 22,
  },
  'voyage.inquiryTimeLine': {
    content: 'nTextGuideVoyageInquiryTimeLine',
    position: "left",
    covered: false,
    index: 23,
  },
  'voyage.orderTimeLine': {
    content: 'nTextGuideVoyageOrderTimeLine',
    position: "left",
    covered: false,
    index: 24,
  },
  'inquiryDetail.addServiceItem': {
    content: 'nTextGuideInquiryDetailAddServiceItem',
    position: "bottom",
    index: 25,
  },
  'inquiryDetail.serviceList': {
    content: 'nTextGuideInquiryDetailServiceList',
    position: "right",
    index: 26,
  },
  'inquiryDetail.removeInquiry': {
    content: 'nTextGuideInquiryDetailRemoveInquiry',
    position: "left",
    index: 27,
  },
  'inquiryDetail.publishInquiry': {
    content: 'nTextGuideInquiryDetailPublishInquiry',
    position: "left",
    index: 28,
  },
  'inquiryDetail.continuePublishInquiry': {
    content: 'nTextGuideInquiryDetailContinuePublishInquiry',
    position: "left",
    index: 29,
  },
  'inquiryDetail.quoteNow': {
    content: 'nTextGuideInquiryDetailQuoteNow',
    position: "left",
    index: 29,
  },
  'inquiryDetail.more': {
    content: 'nTextGuideInquiryDetailMore',
    position: "left",
    index: 29,
  },
  'listTable.viewEportsPrice': {
    content: 'nTextGuideListTableViewEportsPrice',
    position: "left",
    index: 30,
  },
  'listTable.viewAgentPrice': {
    content: 'nTextGuideListTableViewAgentPrice',
    position: "left",
    index: 31,
  },
  'quotation.appointAgent': {
    content: 'nTextGuideQuotationAppointAgent',
    position: "left",
    covered: false,
    index: 32,
  },
  'quotation.reQuote': {
    content: 'nTextGuideQuotationReQuote',
    position: "left",
    covered: false,
    index: 33,
  },
  'quotation.messageInput': {
    content: 'nTextGuideQuotationMessageInput',
    position: "top",
    index: 34,
  },
  'bill.actualCost': {
    content: 'nTextGuideBillActualCost',
    position: "top",
    index: 35,
  },
  'bill.preActualCost': {
    content: 'nTextGuideBillPreActualCost',
    position: "top",
    index: 35,
  },
  'bill.accountFor': {
    content: 'nTextGuideBillAccountFor',
    position: "bottom",
    index: 35,
  },
  'bill.accountFrom': {
    content: 'nTextGuideBillAccountFrom',
    position: "bottom",
    index: 35,
  },
  'bill.billStatus': {
    content: 'nTextGuideBillBillStatus',
    position: "left",
    index: 35,
  },
  'bill.chat': {
    content: 'nTextGuideBillchat',
    position: "left",
    index: 35,
  },
  'bill.rejectBill': {
    content: 'nTextGuideBillRejectBill',
    position: "left",
    covered: false,
    index: 35,
  },
  'bill.acceptBill': {
    content: 'nTextGuideBillAcceptBill',
    position: "left",
    covered: false,
    index: 36,
  },
  'bill.bankAccount': {
    content: 'nTextGuideBillBankAccount',
    position: "top",
    index: 37,
  },
  'bill.informEports': {
    content: 'nTextGuideBillInformEports',
    position: "left",
    covered: false,
    index: 38,
  },
  'header.addShip': {
    content: 'nTextGuideHeaderAddShip',
    covered: false,
    position: "bottom",
    index: 39,
  },
  'ship.operation': {
    content: 'nTextGuideShipOperation',
    covered: false,
    position: "left",
    index: 40,
  },
  'header.addFleet': {
    content: 'nTextGuideHeaderAddFleet',
    covered: false,
    position: "bottom",
    index: 41,
  },
  'fleet.operation': {
    content: 'nTextGuideFleetOperation',
    covered: false,
    position: "left",
    index: 42,
  },
  'user.editPassword': {
    content: 'nTextGuideUserEditPassword',
    covered: false,
    position: "right",
    index: 43,
  },
  'user.viewPermissions': {
    content: 'nTextGuideUserViewPermissions',
    covered: false,
    position: "right",
    index: 44,
  },
  'permission.addPosition': {
    content: 'nTextGuidePermissionAddPosition',
    covered: false,
    position: "bottom",
    index: 45,
  },
  'permission.batches': {
    content: 'nTextGuidePermissionBatches',
    covered: false,
    position: "left",
    index: 46,
  },
  'permission.operation': {
    content: 'nTextGuidePermissionOperation',
    covered: false,
    position: "left",
    index: 47,
  },
  'organization.addDept': {
    content: 'nTextGuideOrganizationAddDept',
    covered: false,
    position: "bottom",
    index: 48,
  },
  'organization.staff': {
    content: 'nTextGuideOrganizationStaff',
    covered: false,
    position: "bottom",
    index: 49,
  },
  'organization.editDeptBatch': {
    content: 'nTextGuideOrganizationEditDeptBatch',
    covered: false,
    position: "left",
    index: 50,
  },
  'organization.editPositionBatch': {
    content: 'nTextGuideOrganizationEditPositionBatch',
    covered: false,
    position: "left",
    index: 51,
  },
  'organization.operation': {
    content: 'nTextGuideOrganizationOperation',
    covered: false,
    position: "left",
    index: 52,
  },
  'quotation.inquiryStatus': {
    content: 'nTextGuideQuotationInquiryStatus',
    position: "bottom",
    index: 53,
  },
  'quotation.epcard': {
    content: 'nTextGuideQuotationEpcard',
    position: "bottom",
    index: 54,
  },
  'quotation.detail': {
    content: 'nTextGuideQuotationDetail',
    position: "left",
    index: 55,
  },
  'quotation.addCost': {
    content: 'nTextGuideQuotationAddCost',
    covered: false,
    position: "bottom",
    index: 55,
  },
  'order.orderStatus': {
    content: 'nTextGuideOrderStatus',
    position: "bottom",
    index: 56,
  },
  'order.epcard': {
    content: 'nTextGuideOrderEpcard',
    position: "bottom",
    index: 57,
  },
  'order.orderStatusLabel': {
    content: 'nTextGuideOrderOrderStatusLabel',
    position: "right",
    index: 57,
  },
  'orderDetail.viewReport': {
    content: 'nTextGuideOrderDetailViewReport',
    position: "left",
    index: 58,
  },
  'orderDetail.viewReportPrincipal': {
    content: 'nTextGuideOrderDetailViewReportPrincipal',
    position: "left",
    index: 58,
  },
  'orderDetail.addService': {
    content: 'nTextGuideOrderDetailAddService',
    position: "bottom",
    index: 59,
  },
  'orderDetail.orderCard': {
    content: 'nTextGuideOrderDetailOrderCard',
    position: "bottom",
    index: 60,
  },
  'orderDetail.serviceList': {
    content: 'nTextGuideOrderDetailServiceList',
    position: "right",
    index: 61,
  },
  'orderDetail.edit': {
    content: 'nTextGuideOrderDetailEdit',
    position: "left",
    index: 62,
  },
  'orderDetail.more': {
    content: 'nTextGuideOrderDetailMore',
    position: "left",
    index: 63,
  },
  'orderDetail.viewBill': {
    content: 'nTextGuideOrderDetailViewBill',
    position: "left",
    index: 63,
  },
  'orderDetail.chat': {
    content: 'nTextGuideOrderDetailChat',
    position: "left",
    index: 63,
  },
  'orderDetail.orderEntryOperation': {
    content: 'nTextGuideOrderDetailOrderEntryOperation',
    position: "bottom",
    index: 64,
  },
  'orderDetail.logItemList': {
    content: 'nTextGuideOrderDetailLogItemList',
    covered: false,
    position: "right",
    index: 65,
  },
  'orderDetail.logItemListView': {
    content: 'nTextGuideOrderDetailLogItemListView',
    covered: false,
    position: "right",
    index: 65,
  },
  'orderDetail.upload': {
    content: 'nTextGuideOrderDetailUpload',
    covered: false,
    position: "left",
    index: 66,
  },
  'orderDetail.uploadPrincipal': {
    content: 'nTextGuideOrderDetailUploadPrincipal',
    covered: false,
    position: "left",
    index: 66,
  },
  'orderDetail.sendReport': {
    content: 'nTextGuideOrderDetailSendReport',
    covered: false,
    position: "left",
    index: 67,
  },
};